// <auto-generated />
using AecoPostMortem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AecoPostMortem.Data.Migrations
{
    [DbContext(typeof(PostMortemContext))]
    [Migration("20260817130106_AddStoreMetadata")]
    partial class AddStoreMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("AecoPostMortem.Data.Execution.Agent", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("ParentAgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_agent_id");

                    b.Property<string>("SpawningToolCallId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("spawning_tool_call_id");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_tokens");

                    b.Property<int?>("TotalToolCalls")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_tool_calls");

                    b.HasKey("SessionId", "AgentId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_agent_session");

                    b.HasIndex("SessionId", "ParentAgentId")
                        .HasDatabaseName("ix_agent_parent");

                    b.ToTable("agent", null, t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_agent_cost", "outcome = 'Completed' OR (total_tokens IS NULL AND total_tool_calls IS NULL AND duration_ms IS NULL AND model IS NULL)");
                        });
                });

            modelBuilder.Entity("AecoPostMortem.Data.Execution.Hook", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_kind");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("SessionId", "EventId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_hook_session");

                    b.ToTable("hook", null, t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_hook_owner", "(owner_kind = 'main') = (agent_id IS NULL)");
                        });
                });

            modelBuilder.Entity("AecoPostMortem.Data.Execution.Permission", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_kind");

                    b.Property<string>("RequestedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at");

                    b.Property<string>("ResultKind")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_kind");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.HasKey("SessionId", "EventId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_permission_session");

                    b.ToTable("permission", null, t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_permission_owner", "(owner_kind = 'main') = (agent_id IS NULL)");
                        });
                });

            modelBuilder.Entity("AecoPostMortem.Data.Execution.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("BaseCommit")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_commit");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long?>("CacheWriteTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_write_tokens");

                    b.Property<string>("CopilotVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("copilot_version");

                    b.Property<string>("Cwd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cwd");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<string>("EventSchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_schema_version");

                    b.Property<string>("GitRoot")
                        .HasColumnType("TEXT")
                        .HasColumnName("git_root");

                    b.Property<string>("HeadCommit")
                        .HasColumnType("TEXT")
                        .HasColumnName("head_commit");

                    b.Property<string>("HostType")
                        .HasColumnType("TEXT")
                        .HasColumnName("host_type");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("ModelCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_count");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<long?>("ReasoningTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reasoning_tokens");

                    b.Property<string>("Repository")
                        .HasColumnType("TEXT")
                        .HasColumnName("repository");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.HasKey("SessionId");

                    b.ToTable("session", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AecoPostMortem.Data.Execution.Skill", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("InvokedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("invoked_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_kind");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("PluginName")
                        .HasColumnType("TEXT")
                        .HasColumnName("plugin_name");

                    b.Property<string>("PluginVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("plugin_version");

                    b.HasKey("SessionId", "EventId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_skill_session");

                    b.ToTable("skill", null, t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_skill_owner", "(owner_kind = 'main') = (agent_id IS NULL)");
                        });
                });

            modelBuilder.Entity("AecoPostMortem.Data.Execution.ToolCall", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("McpServerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("mcp_server_name");

                    b.Property<string>("McpToolName")
                        .HasColumnType("TEXT")
                        .HasColumnName("mcp_tool_name");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_kind");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long?>("ResultSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("result_size_bytes");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<bool?>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_name");

                    b.Property<string>("TurnId")
                        .HasColumnType("TEXT")
                        .HasColumnName("turn_id");

                    b.HasKey("SessionId", "ToolCallId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_tc_session");

                    b.HasIndex("ToolName")
                        .HasDatabaseName("ix_tc_name");

                    b.HasIndex("SessionId", "Path")
                        .HasDatabaseName("ix_tc_session_path");

                    b.HasIndex("SessionId", "ToolName")
                        .HasDatabaseName("ix_tc_session_name");

                    b.HasIndex("ToolName", "Success")
                        .HasDatabaseName("ix_tc_name_success");

                    b.ToTable("tool_call", null, t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_tool_call_owner", "(owner_kind = 'main') = (agent_id IS NULL)");
                        });
                });

            modelBuilder.Entity("AecoPostMortem.Data.Execution.Turn", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("TurnId")
                        .HasColumnType("TEXT")
                        .HasColumnName("turn_id");

                    b.Property<string>("AbortReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("abort_reason");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_kind");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.HasKey("SessionId", "TurnId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_turn_session");

                    b.ToTable("turn", null, t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_turn_owner", "(owner_kind = 'main') = (agent_id IS NULL)");
                        });
                });

            modelBuilder.Entity("AecoPostMortem.Data.Execution.WriteUnit", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<string>("AddedContent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("added_content");

                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_kind");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("ToolCallId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_call_id");

                    b.HasKey("SessionId", "EventId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_write_unit_session");

                    b.ToTable("write_unit", null, t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_write_unit_owner", "(owner_kind = 'main') = (agent_id IS NULL)");
                        });
                });

            modelBuilder.Entity("AecoPostMortem.Data.RawEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ByteOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_offset");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<string>("ProviderVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_version");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_raw_type");

                    b.HasIndex("SessionId", "Sequence")
                        .HasDatabaseName("ix_raw_session_seq");

                    b.HasIndex("SourceFile", "ByteOffset", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_identity");

                    b.ToTable("raw_event", (string)null);
                });

            modelBuilder.Entity("AecoPostMortem.Data.StoreMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("store_metadata", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
