// <auto-generated />
using AecoPostMortem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AecoPostMortem.Data.Migrations
{
    [DbContext(typeof(PostMortemContext))]
    [Migration("20260817054634_CreateRawEvent")]
    partial class CreateRawEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("AecoPostMortem.Data.RawEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ByteOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_offset");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<string>("ProviderVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_version");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_raw_type");

                    b.HasIndex("SessionId", "Sequence")
                        .HasDatabaseName("ix_raw_session_seq");

                    b.HasIndex("SourceFile", "ByteOffset", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_raw_identity");

                    b.ToTable("raw_event", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
